### ISSUE TITLE
something wrong with 1000 unit

### ISSUE THREAD

**Issue by wangchou** [Greatdane/Convert-Numbers-to-Japanese#5]
1万1000 = いちまんいっせん **not いちまんせん**
1000万 = いっせんまん or せんまん
1億1000万 = いちおくいっせんまん **not いちおくせんまん**

**Comment by Greatdane** [comment]
Good catch, let me fix this.

**Comment by Greatdane** [comment]
10000000;
千万 > ー千万
せんまん > いっせんまん
sen man > issen man

11000;
一万千 > 一万一千
いちまんせん > いちまんいっせん
ichi man sen > ichi man issen

110000000;
一億千万 > 一億一千万
いちおくせんまん > いちおくいっせんまん
ichi oku sen man > ichi oku issen man

Basically, as @wangchou said, general rule for 1000 is, if number is greater than 10000, then all the 1000 should be 「いっせん」
